name: Update README with the "Redes Neurais Artificiais - ptBR.pdf" file size

on:
  push:
    branches:
      - master
    paths:
      - "docs/Articles/pt-br/Redes Neurais Artificiais - ptBR.pdf"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install jinja2

      - name: Execute update README script
        run: python scripts/update_readme.py

      - name: Setup GitHub actions user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Changes commit and push
        run: |
          git add README.md
          git commit -m ":memo:docs: Auto README update - $(date +'%m/%d/%Y')"
          git push
